default_platform(:android)

platform :android do
  desc "Build signed AAB"
  lane :build_aab do
    root = File.expand_path("..", __dir__)

    Dir.chdir(root) do
      sh "flutter pub get"
      sh "flutter build appbundle --release --no-tree-shake-icons"
    end
  end
end