name: Android Release (AAB)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.18-8/x64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.2
          channel: stable

      - name: Install Ruby & Fastlane
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          gem install fastlane

      # 🔑 Decode keystore
      - name: Decode Android keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-keystore.jks

      # 🧾 Generate key.properties
      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=app/release-keystore.jks
          EOF

      - name: Flutter pub get
        run: flutter pub get

      - name: Build AAB with Fastlane
        run: fastlane android build_aab

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/bundle/release/*.aab